CREATE TABLE "JDBCTABLE"
(
  "ROWID_" ROWID,
  "UROWID_" UROWID (4000),
  "CHAR_BYTE" CHAR(1 CHAR),
  "CHAR_CHAR" CHAR(1 CHAR),
  "NCHAR_" NCHAR(20),
  "VARCHAR_BYTE_20"  VARCHAR2(20 BYTE),
  "VARCHAR_CHAR_20"  VARCHAR2(20 CHAR),
  "VARCHAR2_BYTE_20" VARCHAR2(20 BYTE),
  "VARCHAR2_CHAR_20" VARCHAR2(20 CHAR),
  "NVARCHAR2_20" NVARCHAR2(20),
  "INTEGER_" NUMBER(*,0),
  "LONG_" LONG,
  "INT_" NUMBER(*,0),
  "FLOAT_" FLOAT(126),
  "NUMBER_2_3" NUMBER(3,2),
  "DOUBLE_PRECISION" FLOAT(126),
  "DATE_"                      DATE,
  "TIMESTARMP"                 TIMESTAMP (6),
  "TIMESTARMP_TIME_ZONE"       TIMESTAMP (6) WITH TIME ZONE,
  "TIMESTARMP_LOCAL_TIME_ZONE" TIMESTAMP (6) WITH LOCAL TIME ZONE,
  "CLOB_" CLOB,
  "NCLOB_" NCLOB,
  "BLOB_" BLOB
)
SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS" LOB
  (
    "CLOB_"
  )
STORE AS BASICFILE
(
TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION NOCACHE LOGGING
)
LOB
  (
    "NCLOB_"
  )
STORE AS BASICFILE
(
TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION NOCACHE LOGGING
)
LOB
  (
    "BLOB_"
  )
STORE AS BASICFILE
(
TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION NOCACHE LOGGING
) ;